### ISSUE TITLE
Get introduction blurbs for each of the host teams

### ISSUE THREAD

**Issue by NathanDuPont** [SoCal-Showdown/socal-showdown-web#11]
Currently, we only display the photos and numbers of the teams hosting the event. This section may be more impactful if we include a concise blurb for each of the host teams, to allow others to get to know us better.

- [ ] Determine what we should include in the information for each of the host teams
- [ ] Gather the information from thebluealliance / the teams themselves
- [ ] Add to the wireframe website

**Comment by mokatsu25** [comment]
@NathanDuPont could we use the "About Us" paragraphs or mission statements of the host teams from each of their team websites?

**Comment by NathanDuPont** [comment]
@mokatsu25  I think that's a great idea! May be good to confirm with teams to make sure that using those is what they would prefer - but if you want to draft up a section including the mission statements for each of the teams, I can communicate with the other teams to make sure it looks good to them!

**Comment by mokatsu25** [comment]
@NathanDuPont I made a draft message for each team on the website if you want to take a look! and yes, please communicate and ask the teams if the messages work for them. also, do you happen to have the team logos too? i was thinking of putting them alongside the messages
