### ISSUE TITLE
Install and configure ESLint and Prettier

### ISSUE THREAD

**Issue by NathanDuPont** [SoCal-Showdown/socal-showdown-web#15]
To keep our project development consistent and easy to follow, we need to install ESLint and Prettier to provide linting and formatting services, respectively. 

- [ ] Install and configure ESLint into the project. Add some documentation to the README to explain what this tool is, and how it works
- [ ] Install and configure Prettier into the project. Add some documentation to the README to explain what this tool is, and how it works
- [ ] Update the npm scripts so developers can run linting, formatting and both through commands (helpful tip - making rules postfixed with `:check` will allow for a helpful way to determine _if_ code follows linting and formatting rules, so we can run it in CI)
- [ ] Add linting and formatting checks in CI, to run on all pushes

**Comment by ThePotatoArchivist** [comment]
@NathanDuPont Do we want to add a commit hook so that whenever someone commits it automatically fixes and formats the code first?
